config/routes.rb
Music::Application.routes.draw do
  get "songs/index"

  match "songs/upload", :as => "upload"  
  match "songs/delete", :as => "delete"  
    
  root :to => "songs#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
  	@songs = Hash.new

    # loop music folder contents into hash
  	Dir.glob('public/music/*.mp3').each do |file|
  		mp3 = Mp3Info.open(file)

  		@songs["#{mp3.tag.title}"] = {
  			:artist => "#{mp3.tag.artist}",
  			:album => "#{mp3.tag.album}",
  			:year => "#{mp3.tag.year}",
  			:tracknum => "#{mp3.tag.tracknum}",
  			:comments => "#{mp3.tag.comments}",
  			:genre => "#{mp3.tag.genre_s}"
  		}
  	end
  end

  def upload
    begin
      # loop through array POST for each song as ActionDispatch::Http::UploadedFile
      params[:mp3file].each do |file|
        # create new empty file
        File.open("public/music/#{file.original_filename}", 'wb') do |f|
          f.write(file.read)
          f.fsync
        end

        # grab mp3 details & rename
        mp3 = Mp3Info.open("public/music/#{file.original_filename}")
        File.rename("public/music/#{file.original_filename}", "public/music/#{mp3.tag.artist} - #{mp3.tag.title}.mp3")
      end

      redirect_to root_path
    rescue
      render :text => "#{Mp3Info.open(params[:mp3file][0])}"
    end
  end

  def delete
    if (params[:song])
      File.delete("public/music/#{params[:song]}")
      redirect_to root_path
    else
      render :text => "No song was found to delete!"
    end
  end

  private

  def sanitize_filename(file_name)
    just_filename = File.basename(file_name)
    just_filename.sub(/[^\w\.\-]/,'_')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper

	def download_url_for(song_key)
		"../music/#{song_key}.mp3"
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mp3app</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js" %>
  <%= javascript_include_tag "application.js" %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="container">
<%= yield %>
</div>
</body>
</html>

app/views/songs/index.html.erb
<h2>Listen to a MP3 with HTML5 Audio</h2> 
<section id="audio">  
</section>  

<h2>Upload a Song</h2>
<%= form_tag upload_path, :method => "post", :multipart => true do %>
    <%= file_field_tag "mp3file[]", :accept => "audio/*", :multiple => "multiple" %><br />
    <%= submit_tag "Upload" %>
<% end %>

<section id="main">
    <h2>Download and Delete Existing MP3's</h2>  

    <table>  
    <% @songs.each_with_index do |(key, value)| %>  
        <tr>
            <td><%= "#{value[:artist].to_s} - #{key}" %></td>
            <td><%= link_to "HTML5 Audio", download_url_for("#{value[:artist].to_s} - #{key}"), :class => "html5" %></td>
            <td><%= link_to "Download", download_url_for("#{value[:artist].to_s} - #{key}") %>
            <td><%= link_to "Delete",  "songs/delete/?song=#{value[:artist].to_s} - #{key}.mp3", :confirm => 'Are you sure you want to delete ' + key + '?' %></td>
        </tr>  
    <% end %>  
    </table>
</section>

<script>
$(document).ready(function() {  
    var audioSection = $('section#audio');  
    $('a.html5').click(function() {  
  
        var audio = $('<audio>', {  
             controls : 'controls'  
        });  
  
        var url = $(this).attr('href');  
        $('<source>').attr('src', url).appendTo(audio);  
        audioSection.html(audio);  
        return false;  
    });  
});
</script>